### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by eisoab** [gogulan-k/FID-Net#2]
I installed fidnet from scratch and tried 

fidnet run-examples 

but get a long trace that ends with the following error: 

```
[....]
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and 
dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras 
operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:
[...]
```

My impression is some versions of current packages have become incompatible (searching for this error message finds the advice to downgrade to numpy=1.19.5, which may help but just leads to another error message.) 

Could you supply a environment.yml file of a working system with all explicit package versions? 

-E

**Comment by TiagoLopesGomes** [comment]
Got it to work by using tensorflow 2.14

Cheers,

Tiago

**Comment by eisoab** [comment]
That worked, thanks!
Eiso

**Comment by Gerardwx** [comment]
@TiagoLopesGomes Which Python version are you using? I'm still getting errors with Python 3.10

**Comment by TiagoLopesGomes** [comment]
Hi,

Python version is  3.11.9

Cheers

**Comment by gogulan-k** [comment]
Current environment.yml is working on NMRBox

**Comment by Gerardwx** [comment]
NMRbox doesn't use the environment.yml. We're installing in a Python virtual environment. 

We're using python3.11 and  add the additional requirements attached. 
[requirements.txt](https://github.com/user-attachments/files/16606473/requirements.txt)
